### PR TITLE
Use url_for instead of request.url in security next param

### PR DESCRIPTION
**Pull request by maudetes**
Fix https://github.com/etalab/data.gouv.fr/issues/509.

Uses `url_for(request.endpoint, **request.view_args)` instead of `request.url`.

Some security pages in `udata` also use `next=request.url`. Not sure if the same issue could happen there ?

### CODE REVIEW

**Review by abulte — COMMENTED** [review]
Much more elegant 👌

I think we should fix it everywhere we can. 

Maybe add a test?

Do we know why the loop caused a crash BTW?

**Comment by maudetes** [comment]
> Do we know why the loop caused a crash BTW?

Nope, I couldn't find the reason, and couldn't reproduce it locally. It didn't look like a loop in the log, I'll give it another look.

**Comment by abulte** [comment]
Maybe 20 or 30 clicks on staging

Capture d’écran 2021-09-08 à 17 38 48

**Comment by abulte** [comment]
nginx

```
151.80.35.135 - - [08/Sep/2021:17:38:41 +0200] "GET /fr/login?next=https%3A%2F%2Fstaging.data.gouv.fr%2Ffr%2Flogin%3Fnext%3Dhttps%253A%252F%252Fstaging.data.gouv.fr%252Ffr%252Flogin%253Fnext%253Dhttps%25253A%25252F%25252Fstaging.data.gouv.fr%25252Ffr%25252Flogin%25253Fnext%25253Dhttps%2525253A%2525252F%2525252Fstaging.data.gouv.fr%2525252Ffr%2525252Flogin%2525253Fnext%2525253Dhttps%252525253A%252525252F%252525252Fstaging.data.gouv.fr%252525252Ffr%252525252Flogin%252525253Fnext%252525253Dhttps%25252525253A%25252525252F%25252525252Fstaging.data.gouv.fr%25252525252Ffr%25252525252Flogin%25252525253Fnext%25252525253Dhttps%2525252525253A%2525252525252F%2525252525252Fstaging.data.gouv.fr%2525252525252Ffr%2525252525252Flogin%2525252525253Fnext%2525252525253Dhttps%252525252525253A%252525252525252F%252525252525252Fstaging.data.gouv.fr%252525252525252Ffr%252525252525252Flogin%252525252525253Fnext%252525252525253Dhttps%25252525252525253A%25252525252525252F%25252525252525252Fstaging.data.gouv.fr%25252525252525252Ffr%25252525252525252F HTTP/1.1" 502 568 "https://staging.data.gouv.fr/fr/login?next=https%3A%2F%2Fstaging.data.gouv.fr%2Ffr%2Flogin%3Fnext%3Dhttps%253A%252F%252Fstaging.data.gouv.fr%252Ffr%252Flogin%253Fnext%253Dhttps%25253A%25252F%25252Fstaging.data.gouv.fr%25252Ffr%25252Flogin%25253Fnext%25253Dhttps%2525253A%2525252F%2525252Fstaging.data.gouv.fr%2525252Ffr%2525252Flogin%2525253Fnext%2525253Dhttps%252525253A%252525252F%252525252Fstaging.data.gouv.fr%252525252Ffr%252525252Flogin%252525253Fnext%252525253Dhttps%25252525253A%25252525252F%25252525252Fstaging.data.gouv.fr%25252525252Ffr%25252525252Flogin%25252525253Fnext%25252525253Dhttps%2525252525253A%2525252525252F%2525252525252Fstaging.data.gouv.fr%2525252525252Ffr%2525252525252Flogin%2525252525253Fnext%2525252525253Dhttps%252525252525253A%252525252525252F%252525252525252Fstaging.data.gouv.fr%252525252525252Ffr%252525252525252F" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36"
```

```
2021/09/08 17:38:41 [error] 12906#12906: *2508994 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 151.80.35.135, server: staging.data.gouv.fr, request: "GET /fr/login?next=https%3A%2F%2Fstaging.data.gouv.fr%2Ffr%2Flogin%3Fnext%3Dhttps%253A%252F%252Fstaging.data.gouv.fr%252Ffr%252Flogin%253Fnext%253Dhttps%25253A%25252F%25252Fstaging.data.gouv.fr%25252Ffr%25252Flogin%25253Fnext%25253Dhttps%2525253A%2525252F%2525252Fstaging.data.gouv.fr%2525252Ffr%2525252Flogin%2525253Fnext%2525253Dhttps%252525253A%252525252F%252525252Fstaging.data.gouv.fr%252525252Ffr%252525252Flogin%252525253Fnext%252525253Dhttps%25252525253A%25252525252F%25252525252Fstaging.data.gouv.fr%25252525252Ffr%25252525252Flogin%25252525253Fnext%25252525253Dhttps%2525252525253A%2525252525252F%2525252525252Fstaging.data.gouv.fr%2525252525252Ffr%2525252525252Flogin%2525252525253Fnext%2525252525253Dhttps%252525252525253A%252525252525252F%252525252525252Fstaging.data.gouv.fr%252525252525252Ffr%252525252525252Flogin%252525252525253Fnext%252525252525253Dhttps%25252525252525253A%25252525252525252F%25252525252525252Fstaging.data.gouv.fr%25252525252525252Ffr%25252525252525252F HTTP/1.1", upstream: "uwsgi://unix:///tmp/staging-front.sock:", host: "staging.data.gouv.fr", referrer: "https://staging.data.gouv.fr/fr/login?next=https%3A%2F%2Fstaging.data.gouv.fr%2Ffr%2Flogin%3Fnext%3Dhttps%253A%252F%252Fstaging.data.gouv.fr%252Ffr%252Flogin%253Fnext%253Dhttps%25253A%25252F%25252Fstaging.data.gouv.fr%25252Ffr%25252Flogin%25253Fnext%25253Dhttps%2525253A%2525252F%2525252Fstaging.data.gouv.fr%2525252Ffr%2525252Flogin%2525253Fnext%2525253Dhttps%252525253A%252525252F%252525252Fstaging.data.gouv.fr%252525252Ffr%252525252Flogin%252525253Fnext%252525253Dhttps%25252525253A%25252525252F%25252525252Fstaging.data.gouv.fr%25252525252Ffr%25252525252Flogin%25252525253Fnext%25252525253Dhttps%2525252525253A%2525252525252F%2525252525252Fstaging.data.gouv.fr%2525252525252Ffr%2525252525252Flogin%2525252525253Fnext%2525252525253Dhttps%252525
```

uwsgi 

```
Wed Sep  8 17:43:10 2021 - invalid request block size: 4818 (max 4096)...skip
```

This does not seem to kill the uwsgi worker though 🤔

**Comment by maudetes** [comment]
> Maybe add a test?

Is this what you had in mind: https://github.com/etalab/udata-front/pull/4/commits/a2a63ef7b88b6252909dec1e8d3d3ea3d3393a97 ?
 
> Do we know why the loop caused a crash BTW?

Not exactly. When opening the url that failed with a 502 in a new tab, it doesn't crash.

**Review by abulte — APPROVED** [review]
Neat!

**Pull request merged**
